//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comisione
    {
        public Comisione()
        {
            this.ComisionesXProfesors = new HashSet<ComisionesXProfesor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
    
        public virtual ICollection<ComisionesXProfesor> ComisionesXProfesors { get; set; }
    }
}
