//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Curso
    {
        public int Id { get; set; }
        public int Curso { get; set; }
        public int Profesor { get; set; }
        public int Horario { get; set; }
        public string Aula { get; set; }
        public Nullable<int> Cupo { get; set; }
    
        public virtual CursosXGrupo CursosXGrupo { get; set; }
        public virtual Horario Horario1 { get; set; }
        public virtual ProfesoresXCurso ProfesoresXCurso { get; set; }
    }
}
