//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.ComisionesXProfesors = new HashSet<ComisionesXProfesor>();
            this.Detalle_Curso = new HashSet<Detalle_Curso>();
            this.Dias = new HashSet<Dia>();
            this.ProyectosXProfesors = new HashSet<ProyectosXProfesor>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<ComisionesXProfesor> ComisionesXProfesors { get; set; }
        public virtual ICollection<Detalle_Curso> Detalle_Curso { get; set; }
        public virtual ICollection<Dia> Dias { get; set; }
        public virtual ICollection<ProyectosXProfesor> ProyectosXProfesors { get; set; }
    }
}
