//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesDeEstudio
    {
        public PlanesDeEstudio()
        {
            this.PlanesDeEstudioXSedes = new HashSet<PlanesDeEstudioXSede>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Modalidad { get; set; }
    
        public virtual Modalidade Modalidade { get; set; }
        public virtual ICollection<PlanesDeEstudioXSede> PlanesDeEstudioXSedes { get; set; }
    }
}
