//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesore
    {
        public Profesore()
        {
            this.ComisionesXProfesors = new HashSet<ComisionesXProfesor>();
            this.ProfesoresXCursoes = new HashSet<ProfesoresXCurso>();
            this.ProyectosXProfesors = new HashSet<ProyectosXProfesor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Plaza { get; set; }
        public int HorasEnPropiedad { get; set; }
        public string Link { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<ComisionesXProfesor> ComisionesXProfesors { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<ProfesoresXCurso> ProfesoresXCursoes { get; set; }
        public virtual ICollection<ProyectosXProfesor> ProyectosXProfesors { get; set; }
    }
}
