//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesoresXCurso
    {
        public ProfesoresXCurso()
        {
            this.Detalle_Curso = new HashSet<Detalle_Curso>();
        }
    
        public int Id { get; set; }
        public int Profesor { get; set; }
        public Nullable<int> Horas { get; set; }
    
        public virtual ICollection<Detalle_Curso> Detalle_Curso { get; set; }
        public virtual Profesore Profesore { get; set; }
    }
}
